name: pr-closed
concurrency: ${{ github.event.number }}

on:
  pull_request:
    types: [closed]

permissions:
   id-token: write   
   contents: read

env:
  resourceGroupName: pr-${{ github.event.number }}
  
jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group delete \
              --name ${{ env.resourceGroupName }} \
              --yes