name: pr-validation
concurrency: ${{ github.event.number }}

on: pull_request

permissions:
  id-token: write
  contents: read


env:
 resourceGroupName: pr-${{ github.event.number }}
 resourceGroupLocation: westus

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create \
              --name ${{ env.resourceGroupName }} \
              --location ${{ env.resourceGroupLocation }}

      - name: Deploy Bicep Template
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          failOnStdErr: false
          deploymentName: pr-${{ github.run_number }}
          resourceGroupName: ${{ env.resourceGroupName }}
          template: deploy/main.bicep
          parameters: >
            environmentType=Test
              
      - name: Show website hostname
        run: |
          echo "Access the website at this address: https://${{ steps.deploy.outputs.appServiceAppHostName }}"

